// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Road[] roads;
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	public tileToNodesMapEntry tiletonodes;
	/**
	 * 
	 */
	public GameLogger gamelogger;
	/**
	 * 
	 */
	public BuildSettlementCommand buildsettlementcommand;
	/**
	 * 
	 */
	public BuildCityCommand buildcitycommand;
	/**
	 * 
	 */
	public BuildRoadCommand buildroadcommand;

	/**
	 * 
	 * @param gameLogger 
	 */
	public void Board(GameLogger gameLogger) {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getTile() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getNode() {
	}

	/**
	 * 
	 * @return 
	 */
	public Road getRoad() {
	}

	/**
	 * 
	 */
	private void connectNodeToTiles() {
	}

	/**
	 * 
	 * @param player 
	 * @param n1 
	 * @param n2 
	 * @param  
	 */
	private void isRoadConnected(Player player, Node n1, Node n2, boolean ) {
	}

	/**
	 * 
	 * @param road 
	 */
	private void addRoadToBoard(Road road) {
	}

	/**
	 * 
	 * @param player 
	 * @param diceValue 
	 */
	private void produceResource(Player player, int diceValue) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void buildRoad(Player player) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void buildCity(Player player) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void buildSettlement(Player player) {
	}

	/**
	 * 
	 */
	private void assignResources() {
	}

	/**
	 * 
	 */
	private void connectAdjacentNodes() {
	}

	/**
	 * 
	 * @return 
	 * @param node 
	 */
	private boolean settlementDistance(Node node) {
	}

	/**
	 * 
	 * @param robberManager 
	 */
	public void setRobberManager(RobberActionsManager robberManager) {
	}

	/**
	 * 
	 * @param players 
	 */
	public void placeInitialSettlements(Player players) {
	}

	/**
	 * 
	 * @param t 
	 * @return 
	 */
	private boolean shouldSkipTile(Tile t) {
	}

	/**
	 * 
	 * @param t 
	 */
	private void processTileForResource(Tile t) {
	}

	/**
	 * 
	 * @param n 
	 * @param r 
	 */
	private void distributeResourceToPlayer(Node n, Resources r) {
	}

	/**
	 * 
	 * @param player 
	 * @param nodeId1 
	 * @param nodeId2 
	 */
	public void removeRoad(Player player, int nodeId1, int nodeId2) {
	}

	/**
	 * 
	 * @param player 
	 * @param nodeId 
	 */
	public void removeCity(Player player, int nodeId) {
	}

	/**
	 * 
	 * @param player 
	 * @param nodeId 
	 */
	public void removeSettlement(Player player, int nodeId) {
	}
}
