// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Roads[] roads;
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	public tileToNodesMapEntry tiletonodes;

	/**
	 * 
	 */
	public void Board() {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getTile() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getNode() {
	}

	/**
	 * 
	 * @return 
	 */
	public Roads getRoad() {
	}

	/**
	 * 
	 * @param player 
	 * @param diceValue 
	 */
	public void takeTurn(Player player, int diceValue) {
	}

	/**
	 * 
	 */
	private void connectNodeToTiles() {
	}

	/**
	 * 
	 * @param player 
	 * @param n1 
	 * @param n2 
	 */
	private void isRoadConnected(Player player, Node n1, Node n2) {
	}

	/**
	 * 
	 * @param road 
	 */
	private void addRoadToBoard(Roads road) {
	}

	/**
	 * 
	 * @param player 
	 * @param diceValue 
	 */
	private void produceResource(Player player, int diceValue) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void buildRoad(Player player) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void buildCity(Player player) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void buildSettlement(Player player) {
	}
}
