// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Roads[] roads;
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	public tileToNodesMapEntry tiletonodes;

	/**
	 * 
	 * @param tiles 
	 * @param nodes 
	 * @param roads 
	 */
	public void Board(Tile tiles, Node nodes, Roads roads) {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getTile() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getNode() {
	}

	/**
	 * 
	 * @return 
	 */
	public Roads getRoad() {
	}

	/**
	 * 
	 * @param player 
	 * @param tile 
	 */
	public void takeTurn(Player player, Tile tile) {
	}

	/**
	 * 
	 */
	private void connectNodeToTiles() {
	}
}
