// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class HumanPlayer extends Player {
	/**
	 * 
	 */
	private String scanner;
	/**
	 * 
	 */
	public UserInput userinput;
}
