// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class MultiDice {
	/**
	 * 
	 */
	public Dice[] dice;

	/**
	 * 
	 * @param dice 
	 */
	public void addDice(undef dice) {
	}

	/**
	 * 
	 */
	public void MultiDice() {
	}
}
