// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int nodeId;
	/**
	 * 
	 */
	private Building building;

	/**
	 * 
	 * @param id 
	 */
	public void Node(int id) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}

	/**
	 * 
	 * @return 
	 */
	public Building getBuilding() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getNodeId() {
	}

	/**
	 * 
	 * @param nodes 
	 */
	public void setNodes(Node nodes) {
	}
}
