// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public abstract class Player {
	/**
	 * 
	 */
	private int playerId;
	/**
	 * 
	 */
	private int points;
	/**
	 * 
	 */
	private BuildingToIntegerMapEntry[] buildingsMap;
	/**
	 * 
	 */
	private ResourcesToIntegerMapEntry[] resourcesMap;

	/**
	 * 
	 * @param id 
	 */
	public void Player(int id) {
	}

	/**
	 * 
	 * @param points 
	 */
	public void addPoints(int points) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getPlayerId() {
	}

	/**
	 * 
	 */
	private void initBuildings() {
	}

	/**
	 * 
	 */
	private void initResources() {
	}

	/**
	 * 
	 * @param resource 
	 * @param amount 
	 */
	public void addResource(Resources resource, int amount) {
	}

	/**
	 * 
	 * @param building 
	 */
	public void addBuilding(Building building) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getTotalResources() {
	}

	/**
	 * 
	 * @param Player 
	 * @param diceValue 
	 */
	public void takeTurn(Player Player, int diceValue) {
	}

	/**
	 * 
	 */
	public void addRoad() {
	}

	/**
	 * 
	 * @param resource 
	 * @param amount 
	 * @return 
	 */
	public boolean removeResource(Resources resource, int amount) {
	}

	/**
	 * 
	 * @param resource 
	 * @param amount 
	 * @return 
	 */
	public boolean hasResources(Resources resource, int amount) {
	}

	/**
	 * 
	 * @return 
	 */
	public String listResources() {
	}
}
