// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class RobberActionsManager {
	/**
	 * 
	 */
	private Tile currentTile;

	/**
	 * 
	 * @return 
	 */
	public boolean discardResourceCards() {
	}

	/**
	 * 
	 * @param newTile 
	 * @return 
	 */
	public boolean moveRobber(Tile newTile) {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getCurrentTile() {
	}

	/**
	 * 
	 * @param currentPlayer 
	 */
	public void stealResource(Player currentPlayer) {
	}
}
