// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public enum TurnManagerStates {
	/**
	 * 
	 */
	startTurn,
	/**
	 * 
	 */
	doAction,
	/**
	 * 
	 */
	endTurn;
}
