// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class TurnManager {
	/**
	 * 
	 */
	public TurnManagerStates currentState;
	/**
	 * 
	 */
	public TurnManagerStates turnmanagerstates;
	/**
	 * 
	 */
	public RobberActionsManager robberactionsmanager;

	/**
	 * 
	 */
	public void TurnManager() {
	}

	/**
	 * 
	 */
	public void manageTurn() {
	}

	/**
	 * 
	 * @return 
	 */
	public int rollMultiDice() {
	}
}
