// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Roads[] roads;
	/**
	 * 
	 */
	private Tile[] tiles;

	/**
	 * 
	 * @param tiles 
	 * @param nodes 
	 * @param roads 
	 */
	public void Board(Tile tiles, Node nodes, Roads roads) {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getTile() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getNode() {
	}

	/**
	 * 
	 * @return 
	 */
	public Roads getRoad() {
	}
}
