// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.HashMap;
import java.util.Map;

/**
 * The board class represents the game board in the Catan game
 * This mainly stores the board elements and provides access to them through getter methods
 * 
 * @author Nitya Patel
 */
public class Board {
	private Tile[] tiles; //Tiles on board
	private Node[] nodes; //Nodes on board
	private Roads[] roads; //Roads on board

	private Map<Tile,Node[]> tileToNodes= new HashMap<>();
	
	/**
	 * Constructs a Board with tiles, nodes and roads
	 * 
	 * @param tiles array of Tile
	 * @param nodes array of Node
	 * @param roads array of Roads
	 */
	public Board(Tile[] tiles, Node[] nodes, Roads[] roads) {
		this.tiles=tiles;
		this.nodes= nodes;
		this.roads= roads;

		connectNodesToTiles();
	}
	
	/**
	 * Connecting tiles to nodes 
	 */
    private void connectNodesToTiles() {
        for (int i = 0; i < tiles.length; i++) {
            Node[] tileNodes = new Node[6]; // each tile has 6 nodes

            for (int j = 0; j < 6; j++) {
                // just pick some nodes to assign to this tile
                int nodeIndex = (i * 3 + j) % nodes.length;
                tileNodes[j] = nodes[nodeIndex];
            }

            // store the mapping
            tileToNodes.put(tiles[i], tileNodes);
        }
    }

    /**
	 * Get nodes for that tile 
	 * @param tile 
	 * @return array of nodes
	 */
    public Node[] getNodesForTile(Tile tile) {
        return tileToNodes.get(tile);
    }

	/**
	 * @return all tiles on the board
	 */
	public Tile[] getTile() {
		return this.tiles;
	}

	/**
	 * @return all nodes on the board
	 */
	public Node[] getNode() {
		return this.nodes;
	}
	
	/**
	 * @return all roads on the board
	 */
	public Roads[] getRoad() {
		return this.roads;
	}
}




