// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 * 
 */
public class BuildingToIntegerMapEntry {
	/**
	 * 
	 */
	private Building key;
	/**
	 * 
	 */
	private int value;
}
