// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private int roundsPlayed;
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private Board board;

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void playRound() {
	}

	/**
	 * 
	 * @param players 
	 * @param board 
	 */
	public void Game(Player players, Board board) {
	}
}
