// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int playerId;
	/**
	 * 
	 */
	private int points;
	/**
	 * 
	 */
	private BuildingToIntegerMapEntry[] buildingsMap;
	/**
	 * 
	 */
	private ResourcesToIntegerMapEntry[] resourcesMap;

	/**
	 * 
	 * @param id 
	 */
	public void Player(int id) {
	}

	/**
	 * 
	 * @param points 
	 */
	public void addPoints(int points) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getPlayerId() {
	}

	/**
	 * 
	 * @param resource 
	 * @return 
	 */
	public int getResource(Resources resource) {
	}

	/**
	 * 
	 */
	public void takeTurn() {
	}
}
