// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 * Represents the different resources present in a Catan Game
 * (Wool, Brick, Lumber, Grain, Ore, and Nothing)
 */
public enum Resources {
	WOOL,
	BRICK,
	LUMBER,
	GRAIN,
	ORE,
	NOTHING;
}
