// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class ResourcesToIntegerMapEntry {
	/**
	 * 
	 */
	private Resources key;
	/**
	 * 
	 */
	private int value;
}
