// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class Roads extends Building {
	/**
	 * 
	 */
	private Node[] connectedNodes;

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public boolean isConnected(Node node) {
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getConnectedNodes() {
	}

	/**
	 * 
	 * @param nodes 
	 * @param owner 
	 */
	public void Roads(Node nodes, Player owner) {
	}
}
