// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int tileID;
	/**
	 * 
	 */
	private int token;
	/**
	 * 
	 */
	private Resources resource;

	/**
	 * 
	 * @param resource 
	 * @param id 
	 * @param token 
	 */
	public void Tile(Resources resource, int id, int token) {
	}

	/**
	 * 
	 * @return 
	 */
	public Resources getResource() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getTileId() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getToken() {
	}
}
