name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create output folders
        run: |
          mkdir out
          mkdir out_test

      # Compile main source code
      - name: Compile source files
        run: |
          javac -d out $(Get-ChildItem -Recurse -Filter *.java Assignment1_Team5/Code/src | ForEach-Object { $_.FullName })

      # Compile JUnit test files
      - name: Compile test files
        run: |
          javac -cp "out;junit-platform-console-standalone.jar" -d out_test $(Get-ChildItem -Recurse -Filter *.java Assignment1_Team5/Code/test | ForEach-Object { $_.FullName })

      # Download JUnit runner
      - name: Download JUnit Console
        run: |
          curl -L -o junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.2/junit-platform-console-standalone-1.10.2.jar

      # Run tests
      - name: Run JUnit Tests
        run: |
          java -jar junit-platform-console-standalone.jar -cp "out;out_test" --scan-classpath

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          args: >
            -Dsonar.projectKey=Nitya-NP_2AA4_Team5_Assignment1
            -Dsonar.organization=nitya-np
            -Dsonar.sources=Assignment1_Team5/Code/src
            -Dsonar.tests=Assignment1_Team5/Code/test
            -Dsonar.java.binaries=out
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
